### ISSUE TITLE
Flatpak version to install on any kind of Linux distribution?

### ISSUE THREAD

**Issue by Tiger862000** [ultrastares/ultrastar-worldparty#29]
Hi guys,
this project is amazing. Finally, an improvement to the deluxe version.
Will you make a flatpak to allow installation for this masterpiece for all Linux distributions?
Thank you for consideration.

**Comment by Daniel20Ultrastar-es** [comment]
we'll try to make a snap version, but it will take time until new stable release.

**Comment by Tiger862000** [comment]
That would be awesome.

**Comment by jmgomezpoveda** [comment]
I've just tried installing the snap at https://snapcraft.io/install/usdxworldparty/ubuntu (as directed from https://snapcraft.io/usdxworldparty) and apart from requiring me a lot of old libav libraries and their dependencies, all I get is an error like:

```
Could not load any Language File
An unhandled exception occurred at $000000000042B1EA:
EInOutError: 
  $000000000042B1EA
```

Any way to install the software even in a more traditional manner?

**Comment by Daniel20Ultrastar-es** [comment]
That's not an official release, to install WorldParty, have a look in our wiki: https://github.com/ultrastares/ultrastar-worldparty/wiki/Install-WorldParty-on-Ubuntu

**Comment by claudioap** [comment]
An opinion:
Flatpaks are preferable in distros other than Ubuntu. Overall the community tends to prefer more open solutions (snaps are soulbound to Canonical's repos) but there are some technical reasons as well (such as avoiding mount hell and home directory pollution).  Also Canonical has an history of giving up on most things they start and Flatpaks on the other hand are decentralized (you can have your own repos if Flathub is deemed unfit).

Even Ubuntu derivatives such as Mint have decided to strip snaps off the defaults.

In theory both support basically every moderately used distro and are decent enough options. Just throwing my two cents.

**Comment by TeLiXj** [comment]
Finally I'm build a snap version that it's "easy" for me. I waste a month to solver all problems and release this version https://snapcraft.io/ultrastar-worldparty
Only fails to detect all languages, but at least works fine to sing. I will improve it in the next versions.
It's available on arm64 and armhf architectures too. I hope that can be installed on Raspberry 3+ or 4.

**Comment by Javierkaiser** [comment]
Any news of a Flatpak version?

**Comment by TeLiXj** [comment]
According to my last comment we only have a Snap version. Flatpak is not expected.
