### ISSUE TITLE
ffmpeg 4.2 compatibility

### ISSUE THREAD

**Issue by cyberconan** [ultrastares/ultrastar-worldparty#31]
Hi! Can you add support with ffmpeg 4.2? Thanks for all your work!!

**Comment by cyberconan** [comment]
Hi again, I did a dirty solution, comment version control in lib/ffmpeg-4.0/*.pas files and everything compiles well and karaoke launch. Maybe there's no change in new ffmpeg 4.x libraries than affects Ultrastar by the moment? Regards!

**Comment by TeLiXj** [comment]
Fixed by https://github.com/ultrastares/ultrastar-worldparty/commit/0f31c935dd31e9d1b3ed6fa931ca94c295496b74
