### ISSUE TITLE
Crash EListError on Windows 10

### ISSUE THREAD

**Issue by ruifil** [ultrastares/ultrastar-worldparty#33]
We have the following issue.

**Exception class: EListError
Message: Cannot use find on unsorted list**

<img width="311" alt="BugUltrastarEListError" src="https://user-images.githubusercontent.com/1698037/81257234-03d14680-9033-11ea-854d-3ab05814d287.png">

**Comment by TeLiXj** [comment]
Can you explain more?? When appear this error?
Thanks

**Comment by ericbrandwein** [comment]
Happens the same to me. To reproduce it, have an Xbox 360 Controller connected when opening Ultrastar Worldparty.

**Comment by ericbrandwein** [comment]
You should also have "Settings > Game > Activate Gamepad" on.

**Comment by Edi316** [comment]
I can also confirm this error with a connected Dualshock 4 and „Activate Gamepad“=on

**Comment by poupounetjoyeux** [comment]
Same here with game pad ON and X360 wireless controller plugged in

**Comment by Edi316** [comment]
Just FYI:
The problem still exists in 20.12 Beta

![Bildschirmfoto 2020-12-25 um 17 01 50](https://user-images.githubusercontent.com/61267443/103138458-1f2cb700-46d3-11eb-88fe-f6098e4dda80.jpg)

**Comment by TeLiXj** [comment]
Of course, the issue is still open... 
After resolve it I will close it.

**Comment by TeLiXj** [comment]
Anyone can compile the alfa version to check if problem is resolved? I don't have a gamepad here to check it. Thanks :)

**Comment by BanCrash** [comment]
> Anyone can compile the alfa version to check if problem is resolved? I don't have a gamepad here to check it. Thanks :)

I never did it so I'm not sure if I will achieve the compiling following the wiki tutorial, but I'll try.

**Comment by TeLiXj** [comment]
Don't worry, a friend gave me a gamepad and works. Now I have started to fix position in resolutions higher than 800x600.
You will have the correction the next week in the final version

**Comment by BanCrash** [comment]
Ah, okay, perfect then!

**Comment by TeLiXj** [comment]
Job done. As I said you will have all changes in few days.
