### ISSUE TITLE
Crashing if microphones are plugged in on start up Ubuntu 19.10

### ISSUE THREAD

**Issue by netm** [ultrastares/ultrastar-worldparty#34]
Hi there,

Our family loves the app! We have it running on Ubuntu 19.10 and it works well except if we start it with the SingStar microphones plugged in (two in one USB dongle) the app crashes. 

If we unplug them and start the app then plug in the microphones it works well. 

We also can not get a 3rd or 4th mic working, when we plugin another set of Singstar microphones (we have two sets) all we can see in the GUI is the default input, we can't change it, so can only get two channels working.

**Comment by TeLiXj** [comment]
Hi! Yes, the problem is that ALSA can't access to the device. 
In my case I can't play with the first USB connected...

I will try to fix it as soon as possible.

**Comment by TeLiXj** [comment]
Hi again! I had 20.04 version in May but now I'm using 20.10 version with the last game version and all works fine. 
Can you confirm this?
