### ISSUE TITLE
Hang on search

### ISSUE THREAD

**Issue by edouardreg** [ultrastares/ultrastar-worldparty#35]
hello,

I've got a litlle more than 1800 songs. Sometimes (around one search of five (using J + letters….)) the software stop responding when you arrive at the four or five letter in the search field.

Have to kill the process and then restart : all ok for 4-5 research ant then again hang on one more search….

I'm using windows 10 64 bits (last version, hp probook 16Go RAM)

**Comment by Daniel20Ultrastar-es** [comment]
this is fixed in branch: alfa
