### ISSUE TITLE
Mac OS Access violation Error

### ISSUE THREAD

**Issue by buges** [ultrastares/ultrastar-worldparty#37]
Hi

I've compiled the master branch and the alfa branch, both of them compile ok.
And after I use make macosx-standalone-app I get the USDXWorldParty.app

But neither branch runs and gives me this error:

An unhandled exception occurred at $00000001000B441D:
EAccessViolation: Access violation
  $00000001000B441D
  $000000010007A8A5

My system is running Mojave.

Compiling on windows or ubuntu no problem at all.

Thanks in advance for any help

**Comment by TeLiXj** [comment]
Hi! We don't support mac builds because any of us have a mac... we will remove completely all files related in the next versions.
