### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by Jeisson37** [ultrastares/ultrastar-worldparty#38]
Doing the compilation according documentation, after press F9 in atom appear the next error:

<pre>
Target OS: Linux for x86-64
Compiling WorldParty.dpr
switches.inc(93,6) Fatal: Cannot open include file "config-linux.inc"
Fatal: Compilation aborted
Error: /usr/local/bin/ppcx64 returned an error exitcode
</pre>

The SO is Fedora 33, I have followed the instructions of documentation

**Comment by TeLiXj** [comment]
Yes, I forgot to add more instruction to Linux version. We don't have a command created for Fedora, but you can do it manually.
You must have installed this packages: `automake make gcc fpc SDL2_image-devel ffmpeg-devel sqlite-devel freetype-devel lua-devel opencv-devel`
And later you can execute this commands:
```
./autogen.sh
./configure
make
make install
```
All of this is similar as you can see in ./install file created for Ubuntu/Debian.

**Comment by Jeisson37** [comment]
Thanks! It works, however I think is also required <code>Lua 5.3</code> and the actual version is <code>Lua 5.4</code>. I could try downgrade Lua but maybe exists other way of fix this. Thanks for any info about this.
Note: Also required the package <code>portaudio-devel</code>

**Comment by TeLiXj** [comment]
I will upgrade Lua version and remove portaudio requirement in next week stable version. Thanks for that info.
