### ISSUE TITLE
Fix on song click advanced option

### ISSUE THREAD

**Issue by TeLiXj** [ultrastares/ultrastar-worldparty#40]
If you select the second option (select players) you will never go to sing the song after click on next button.

**Comment by TeLiXj** [comment]
now go to the song but many things disappear from screen

**Comment by ThePromidius** [comment]
Did you ever take a look at this? Know where to start searching at?
Honestly never used pascal but there's an app i want to maintain so i guessed trying to take a look at this would be good practice.

**Comment by TeLiXj** [comment]
I supose that was fixed in e0736e551c5ebddd17a13aad3eadd681db0be578
