### ISSUE TITLE
Could not find the default skin Static Violet of theme Fantasy

### ISSUE THREAD

**Issue by jschwartzenberg** [ultrastares/ultrastar-worldparty#48]
With recent revisions, I get this when trying to launch WorldParty:
```
Could not find the default skin Static Violet of theme Fantasy
An unhandled exception occurred at $00041DAC:
EInOutError: Invalid file handle
  $00041DAC

An unhandled exception occurred at $000360B4:
EAccessViolation: 
  $000360B4
```

Any idea how to solve this?

**Comment by TeLiXj** [comment]
what version are you using (windows, compiled in linux, snap, deb)?

**Comment by jschwartzenberg** [comment]
I compiled on Ubuntu 20.04 (Armbian). In the past I could run WorldParty without issues.

Are there debs available (for ARM)?

**Comment by TeLiXj** [comment]
No, only debs for amd64.
Are you using the last version of the repository code? I've compiled just now and executed without that error.

Anyway, you can try to use our new snap version https://snapcraft.io/ultrastar-worldparty
I didn't try to execute it in ARM, but its compiled to it...

**Comment by jschwartzenberg** [comment]
It seems the version in snap doesn't work:
```
julius@tinkerboard:~$ /snap/ultrastar-worldparty/current/game/WorldParty
double free or corruption (out)
Aborted
```

**Comment by TeLiXj** [comment]
you must use the shortcut generated in your desktop menu to execute it

**Comment by jschwartzenberg** [comment]
I couldn't find anything in my menus, but this command does the trick: `snap run ultrastar-worldparty`

Now I need to figure out how to provide access to my songs...

**Comment by TeLiXj** [comment]
The shortcut must be in the games folder.
That command don't work at all because the default charset isn't set (at least no in my Kubuntu 20.10), and every string with non ASCII characters fails in the game. I can't try know, but you could try to run `env LC_ALL=C.UTF-8 snap run ultrastar-worldparty`
The config are in ~/snap/ultrastar-worldparty/current/.ultrastar-worldparty

**Comment by jschwartzenberg** [comment]
I don't have a games folder in the menu. Yeah I couldn't see non-ASCII characters yet.

I found the config, but it seems the application cannot just access my NFS shares as usual. I'm not sure yet how to provide those. Does the application look in a default location for songs?

**Comment by TeLiXj** [comment]
What desktop are you using? Maybe if you search `worldparty` in your apps you could found it.
The default location is in the same directory, you can create a new one called `songs`.
And the snap is opened to use all mounted paths, for example to access to other internal or external hard disk but idk how works with a NFS folder.

**Comment by jschwartzenberg** [comment]
Ah there's no system-wide directory for songs? I'm using XFCE. It's the standard Armbian image (for ASUS Tinkerboard) which uses XFCE by default. In general UltraStar DX/WorldParty works well on this hardware. The only missing bit is VPU acceleration.

**Comment by TeLiXj** [comment]
Yes, I told you in my last message: `~/snap/ultrastar-worldparty/current/.ultrastar-worldparty/songs`. And you can choose as you want in config using options `SongDir1`, `SongDir2`, etc.
I will try to install XFCE to see how add the shortcut. 
I close this issue because I can't find the error and the install script will be removed in future versions.

**Comment by jschwartzenberg** [comment]
So for completion, to have a system-wide songs directory, one can do this:
```
root@tinkerboard:~# mkdir /var/snap/ultrastar-worldparty/common/songs
root@tinkerboard:~# mount -o bind /nas/karaoke /var/snap/ultrastar-worldparty/common/songs
```
Then edit `~/snap/ultrastar-worldparty/current/.ultrastar-worldparty/config.ini` and set `SongDir1` to `/var/snap/ultrastar-worldparty/common/songs`.

You'll have to edit the configuration per user, but the mount point can be configured system-wide with automount or fstab.

Thanks a lot for all the help and for providing these Snaps!
