### ISSUE TITLE
Need to restart about 4-5 times to get through song loading

### ISSUE THREAD

**Issue by jschwartzenberg** [ultrastares/ultrastar-worldparty#54]
When I start UltraStar WorldParty, the first few times it shows "loading song <songname>" at the bottom and when I try to enter the game I get "Wait for loading all the songs". However it just hangs on a song at that point, it's not proceeding. When I restart the game about 4-5 times the loading text does not show up anymore at some point and I can enter the game immediately. I have about 854 songs.

**Comment by TeLiXj** [comment]
what processor model do you have?

**Comment by jschwartzenberg** [comment]
It's the board for which you recommended me the snap package, which I'm using:
```
julius@tinkerboard:~$ lscpu
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               1
Model name:          Cortex-A17
Stepping:            r0p1
Frequency boost:     disabled
CPU max MHz:         1800.0000
CPU min MHz:         126.0000
BogoMIPS:            57.60
Flags:               half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
```

**Comment by TeLiXj** [comment]
as I expected an ARM... I suspect that the thread pascal library for this architecture is a bit buggy (more than amd64 xD)
I have to close as won't fix because it doesn't depend on me, it's the library

**Comment by jschwartzenberg** [comment]
Alright, thanks for the info, good to know! Do you know if this issue is reported/tracked somewhere else?

**Comment by TeLiXj** [comment]
no, I use it to create the multi-thread loading songs and know how works
I'm don't saying that it's the library itself (or yes, I don't know), it's the library in this code because have many memory leaks
for example if you press F5 to reload songs works fine the first time always (at least on my machine) but if you continue using it finally fails

**Comment by jschwartzenberg** [comment]
Yeah I think it I recognize this, I also get crashes on start-up from time to time and retrying to start the program does the trick then. Maybe it would be good to obtain a stack-trace or find another way to report this issue upstream.

**Comment by watho** [comment]
Just want to tell you that this is no arm-specific issue. I have the same problems (occasionally crashes at startup, multiple restarts for successfully reading the library) on amd64.
